name: Setup project
description: Setup project and build for deployment

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build app
      run: npm run build
