name: Deploy

on:
  workflow_dispatch:
    inputs:
      deploy-vercel:
        description: 'Enable Vercel deployment'
        type: boolean
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run app
        run: npm run start

      - name: Deploy to Vercel
        if: ${{ github.event.inputs.deploy-vercel }}
        run: npx vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
